---
language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_install:
    - |
      openssl aes-256-cbc -d \
          -K $encrypted_2234089e6802_key \
          -iv $encrypted_2234089e6802_iv \
          -in auth.json.enc \
          -out auth.json

install:
    - composer install

script:
    - php vendor/bin/phpcs
