---
language: php

php:
  - 7.1
  - 7.2
  - 7.3

install:
    - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in auth.json.enc -out auth.json -d
    - composer install

script:
    - php vendor/bin/phpcs
