---
language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.3
  - 7.4snapshot

matrix:
  allow_failures:
    - php: 7.4snapshot

before_install:
    - |
      openssl aes-256-cbc -d \
          -K $encrypted_2234089e6802_key \
          -iv $encrypted_2234089e6802_iv \
          -in auth.json.enc \
          -out auth.json

install:
    - travis_retry composer install -n --prefer-dist

script:
    - composer run-script phpcs
